### ISSUE TITLE
Change cursor to a hand on tooltip button

### ISSUE THREAD

**Issue by asjongers** [big-data-europe/ember-swarm-ui-engine#3]
![image](https://user-images.githubusercontent.com/18548258/32953641-1ebb81c0-cbb1-11e7-972b-659e601d7d0d.png)

**Comment by lordblendi** [comment]
This issue is about the ( i ) icon. Solution:

``` css
.the-good-class {
    cursor: pointer;
}
```
